services:
  - type: web
    name: graduation-project-api
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
